name: 🦊 Build Firefox

on: 
    workflow_dispatch:
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
#             - uses: actions/setup-node@v3
#               with:
#                 node-version: 18
#                 cache: npm
            - name: Install dependencies
              run: npm ci --production
            - name: Run Build
              run: npm run build:firefox
            - name: Create dist folder
              run: mkdir dist
            - name: Zip Extension
              run: zip -r dist/wasteof-plus-firefox.zip . -x .git/ -x manifest_chromium.json -x manifest_firefox.json -x dist/
            - uses: actions/upload-artifact@v3
              with:
                name: my-artifact
                path: dist/wasteof-plus-firefox.zip
